### ISSUE TITLE
Docker file: installation of openjdk-8-jdk-headless not required

### ISSUE THREAD

**Issue by agaldemas** [Engineering-Research-and-Development/iotagent-opcua#5]
Hello,
in the Dockerfile, the line (RUN \\) `apt-get install -y git netcat openjdk-8-jdk-headless && \`
openjdk is not needed, since there's no java software to run !

**Comment by gabrieledeluca** [comment]
Hello,
openjdk is necessary in order to run the mapping_tool.jar: a tool to create a sample configuration file reading from OPC UA server on execution time. The tool doesn't start if you have already created a config file (config.json).
You can find major details in the documentation (https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/docs/user_and_programmers_manual.md)

**Comment by agaldemas** [comment]
OK, sorry for missing the point
