### ISSUE TITLE
[MUST] Dockerization must protect Username/Password ENV

### ISSUE THREAD

**Issue by jason-fox** [Engineering-Research-and-Development/iotagent-opcua#7]
With the addition of Oauth2 support authentication with  using FIWARE Keyrock, usernames and passwords are now part of the Docker environment variables. Currently these can only be passed using plain text. The addition of **Docker Secrets** support protecting these passwords is necessary to plug a potential security flaw.

This is a simple addition of a script   in the same manner as PostGres  (and relevant documentation of course) Cygnus does it already. This flaw relates to all IoT Agents.

https://github.com/telefonicaid/iotagent-node-lib/pull/726#discussion_r242214046

Within the Docker container, Passwords etc can only be passed protected by Docker Secrets
- MUST  requirement from TSC

**Comment by gabrieledeluca** [comment]
Hello @jason-fox ,
we have updated the [docker-compose](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/docker-compose/docker-compose.yml) file in order to read environment variables (about IDM authentication) from a text [file](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/docker-compose/age_idm_auth.txt) using docker secrets (instructions contained [here)](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/docker-compose/docker_compose_instructions.md).

Furthermore we have updated [Dockerfile](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/Dockerfile) with the entrypoint [script](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/docker-entrypoint.sh).

How does that sound?
